name: 'iterable'

version: '1.0.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  iterable:
    +materialized: table
    +schema: iterable
    intermediate:
      +materialized: view
      +schema: int_iterable
      int_iterable__list_user_history:
        +materialized: table
    staging:
      +materialized: table
      +schema: stg_iterable
      tmp:
        +materialized: view
vars:
  iterable:
    campaign_history: "{{ source('iterable', 'campaign_history') }}"
    campaign_label_history: "{{ source('iterable', 'campaign_label_history') }}"
    campaign_list_history: "{{ source('iterable', 'campaign_list_history') }}"
    campaign_metrics: "{{ source('iterable', 'campaign_metrics') }}"
    campaign_suppression_list_history: "{{ source('iterable', 'campaign_suppression_list_history') }}"
    channel: "{{ source('iterable', 'channel') }}"
    event: "{{ source('iterable', 'event') }}"
    event_extension: "{{ source('iterable', 'event_extension') }}"
    list: "{{ source('iterable', 'list') }}"
    message_type: "{{ source('iterable', 'message_type') }}"
    template_history: "{{ source('iterable', 'template_history') }}"
    user_history: "{{ source('iterable', 'user_history') }}"
    user_unsubscribed_channel: "{{ source('iterable', 'user_unsubscribed_channel') }}"
    user_unsubscribed_message_type: "{{ source('iterable', 'user_unsub_message_type') }}"

    iterable_event_extension_pass_through_columns: []
    iterable_user_history_pass_through_columns: []

    iterable__event_metrics:
    - "emailClick"
    - "emailUnSubscribe"
    - "emailComplaint"
    - "customEvent"
    - "emailSubscribe"
    - "emailOpen"
    - "pushSend"
    - "smsBounce"
    - "pushBounce"
    - "inAppSendSkip"
    - "smsSend"
    - "inAppSend"
    - "pushOpen"
    - "emailSend"
    - "pushSendSkip"
    - "inAppOpen"
    - "emailSendSkip"
    - "emailBounce"
    - "inAppClick"
    - "pushUninstall"
